# action.yml
name: 'Pack Docker Action'
description: 'Run the Cloud Native Buildpacks Pack CLI'
author: 'dfreilich'
branding:
  color: blue
  icon: layers   # from https://feathericons.com/

runs:
  using: 'docker'
  image: 'docker://buildpacksio/pack'
