name: autorelease

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      tag_name:
        required: false
        description: The release tag to distribute. If empty, it will bump the latest version.

jobs:
  release-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: last-version
        uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: |
            let tag = (context.payload.inputs && context.payload.inputs.tag_name)
              || (await github.repos.getLatestRelease({owner: context.repo.owner,repo: context.repo.repo})).data.name;

            if (!tag) {
              throw "ERROR: unable to determine tag";
            }

            return tag.replace(/^v/, '');
      - name: Bump Release
        id: bump-version
        run: |
          v=${{ steps.version.outputs.result }}
          bump=$(echo "${v%.*}.$((${v##*.}+1))")
          major=$(echo "${v%.*}")
          echo $bump
          echo $major
          echo "ACTION_TAG=v${bump}" >> $GITHUB_ENV
          echo "MAJOR_TAG=v${major}" >> $GITHUB_ENV
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.ACTION_TAG }}
          release_name: ${{ env.ACTION_TAG }}
          body: |
            # pack-action ${{ env.ACTION_TAG }}
            This is an automated release of the Pack Action, incorporating a dependency update. For detailed usage
            documentation, check out the the documentation [here](https://github.com/dfreilich/pack-action#usage)
      - name: Update major tag
        run: |
          git tag ${{ env.MAJOR_TAG }}
          git push -f origin ${{ env.MAJOR_TAG }}
